interface ISeoImageProps {
  source: string;
  title?: string;
}

export default function SeoImage({ title, source }: ISeoImageProps) {
  const api = "https://i.microlink.io/";
  const cardUrl = `https://cards.microlink.io/?preset=tinybird&p=2gaWPD4KICA8RmxleAogICAgc3g9e3sKICAgICAgZmxleERpcmVjdGlvbjogJ2NvbHVtbicsCiAgICAgIGp1c3RpZnlDb250ZW50OiAnY2VudGVyJywKICAgICAgYWxpZ25JdGVtczogJ2NlbnRlcicsCiAgICAgIGJnOiAnIzI1MjgzRCcsCiAgICAgIHBsOiA1LAogICAgICBwcjogNSwKICAgIH19CiAgPgogICAgPExpbmsKICAgICAgaHJlZj0naHR0cHM6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3MyP2ZhbWlseT1JbnRlcjp3Z2h0QDQwMCZkaXNwbGF5PWJsb2NrJwogICAgICByZWw9J3N0eWxlc2hlZXQnCiAgICAvPgogICAgPEZsZXgKICAgICAgYXM9J2hlYWRlcicKICAgICAgc3g9e3sKICAgICAgICBwb3NpdGlvbjogJ2Fic29sdXRlJywKICAgICAgICB0b3A6IDAsCiAgICAgICAgbGVmdDogNSwKICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgYWxpZ25JdGVtczogJ2NlbnRlcicsCiAgICAgICAgd2lkdGg6ICcxMDAlJywKICAgICAgICBtdDogJzNlbScsCiAgICAgIH19CiAgICA-CiAgICAgIDxJbWFnZQogICAgICAgIHN4PXt7CiAgICAgICAgICB3aWR0aDogJzI2cHgnLAogICAgICAgIH19CiAgICAgICAgc3JjPSdodHRwczovL3Jlcy5jbG91ZGluYXJ5LmNvbS9hbGJpbi1ncm9lbi9pbWFnZS91cGxvYWQvZl9hdXRvLHFfYXV0byx3XzEwMC92MTYwMjkzNTUwMi9sb2dvX3V3czEwZS5zdmcnCiAgICAgIC8-CiAgICAgIDxGbGV4PgogICAgICAgIDxUZXh0CiAgICAgICAgICBzeD17ewogICAgICAgICAgICBwbDogMywKICAgICAgICAgICAgZGlzcGxheTogJ2lubGluZS1ibG9jaycsCiAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDQwMCwKICAgICAgICAgICAgZm9udFNpemU6ICcyMnB4JywKICAgICAgICAgICAgZm9udEZhbWlseTogJ0ludGVyJywKICAgICAgICAgICAgY29sb3I6ICcjRkZGJywKICAgICAgICAgICAgbGluZUhlaWdodDogJzE0MCUnLAogICAgICAgICAgfX0KICAgICAgICA-CiAgICAgICAgICBBbGJpbiBHcm9lbgogICAgICAgIDwvVGV4dD4KICAgICAgICB7cXVlcnkuc3VidGl0bGUgJiYgKAogICAgICAgICAgPFRleHQKICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICBkaXNwbGF5OiAnaW5saW5lLWJsb2NrJywKICAgICAgICAgICAgICBmb250V2VpZ2h0OiA0MDAsCiAgICAgICAgICAgICAgZm9udFNpemU6ICcyMnB4JywKICAgICAgICAgICAgICBmb250RmFtaWx5OiAnSW50ZXInLAogICAgICAgICAgICAgIGNvbG9yOiAnIzFGQ0M4MycsCiAgICAgICAgICAgICAgbGluZUhlaWdodDogJzE0MCUnLAogICAgICAgICAgICB9fQogICAgICAgICAgPgogICAgICAgICAgICAve3F1ZXJ5LnN1YnRpdGxlfQogICAgICAgICAgPC9UZXh0PgogICAgICAgICl9CiAgICAgIDwvRmxleD4KICAgIDwvRmxleD4KCiAgICA8RmxleCBhcz0nY29udGVudCc-CiAgICAgIDxUZXh0CiAgICAgICAgc3g9e3sKICAgICAgICAgIGRpc3BsYXk6ICdpbmxpbmUnLAogICAgICAgICAgZm9udFdlaWdodDogNDAwLAogICAgICAgICAgZm9udFNpemU6ICc0MnB4JywKICAgICAgICAgIGZvbnRGYW1pbHk6ICdJbnRlcicsCiAgICAgICAgICBjb2xvcjogJyNGRkYnLAogICAgICAgICAgbGluZUhlaWdodDogJzE0MCUnLAogICAgICAgIH19CiAgICAgID4KICAgICAgICB7cXVlcnkudGV4dH0KICAgICAgPC9UZXh0PgogICAgPC9GbGV4PgogIDwvRmxleD4KPC8-&subtitle=blog&text=${title}`;
  const image = `${api}${encodeURIComponent(cardUrl)}`;

  return (
    <>
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:image" content={source || image} />
      <meta property="og:image" content={source || image} />
      <meta itemProp="image" content={source || image} />
      <meta content={source || image} name="image" />
    </>
  );
}
